@startuml programmatic_store_local_services_info
!theme aws-orange

skinparam BackgroundColor white
skinparam actorstyle awesome
autonumber 1

'participant "Mail\npoller" as mail_poller
'participant "Mail\nlistener" as mail_listener
'participant "Mail\nfilterer" as mail_filterer
'participant "Booking\ntracker" as booking_tracker
'participant "GDS\nconnector" as gds_connector
'participant "Sharer" as sharer
'participant "Social Media\nconnector" as social_connector
'participant "Help\nGateway" as help_gateway
'participant "Data\nExporter" as data_exporter
'participant "Analytics\nGenerator" as analytics_generator
'participant "Web" as web
'participant "App" as app
''participant "Notifier" as notifier
''actor "User" as user


participant "Analytics\nExporter" as analytics_exporter
participant "Analytics\nStorage" as analytics_storage
participant "Booking\ninterface" as booking_interface
participant "Third parties\nComplementary services\nconnector" as third_parties_connector
participant "Third parties API" as third_parties_api
participant "Booking\nstorage" as booking_storage

analytics_exporter -> analytics_storage: Retrieve report of often used services
return Report data
analytics_exporter -> booking_interface: Trigger retrieval of index information
booking_interface -> third_parties_connector: Get current info on services and events
third_parties_connector -> third_parties_api: Get data
return Data
third_parties_connector --> booking_interface
booking_interface -> booking_storage: Store updated info
return Store OK

@enduml
