@startuml
'!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml
!include <c4/C4_Container.puml>  

'ref http://plantuml.com/stdlib
!include <office/Users/user.puml>
!include <office/Users/mobile_user.puml>

LAYOUT_WITH_LEGEND()

skinparam linetype ortho

title Container diagram for Internet Banking System

Person(customer  , Customer , "<$user>   <$mobile_user>" )

System_Boundary(c1, "The Road Warrior") {
'    Container(web_app, "Web Application", "Java, Spring MVC", "Delivers the static content and the Internet banking SPA")
'    Container(spa, "Single-Page App", "JavaScript, Angular", "Provides all the Internet banking functionality to cutomers via their web browser")
'    Container(mobile_app, "Mobile App", "C#, Xamarin", "Provides a limited subset of the Internet banking functionality to customers via their mobile device")
together {
Container(booking_interface, "Booking interface", "", "access to the database")
ContainerDb(booking_db, "Booking storage", "SQL Database", "Keep **PNR** info and update of the travels")
}

Container(booking_tracker, "Booking tracker", "", "make sure we get update from")
'    Container(backend_api, "API Application", "Java, Docker Container", "Provides Internet banking functionality via API")
Container(analytics, "Analytics", "", "Data reporter\nAnaytics storage\nAnalytics exporter")
Container(mail_poller, "Mail integration", "", "poller\nlistener\nfilterer\n\nscrape mails from the active users")
Container(collector_agencies, "Collector Agencies", "...", "Interact with Agencies and collect booking updates")

together {
Container(notifier, "Update notifier", "", "Generate update for the user")
Container(help, "help gateway", "...", "")
Container(front_end, "Front end", "...", "")
Container(sharer, "Share", "", "allow for sharing trip")
}

}


System_Ext(email_provider, "E-mail provider", "User mail provider.")
System_Ext(third_parties, "Third parties")
System_Ext(social_media, "Social Media", "Different Social media")
System_Ext(ext_agencies, "External Agencies", "GDS [Amadeus|Travelport|Sabre]\nAgencies [hotel/flight/car] supplier")
 
'Rel(customer, web_app, "Uses", "HTTPS")
'Rel(customer, spa, "Uses", "HTTPS")
'Rel(customer, mobile_app, "Uses")
notifier -[hidden]- mail_poller

mail_poller -[hidden]- collector_agencies

Rel_Back(customer, notifier, "updates")
Rel(customer, front_end, "updates")

Rel(front_end, booking_interface, "")

Rel_Back_Neighbor(email_provider, mail_poller, "")
Rel_Neighbor(mail_poller, booking_interface, "")

Rel(collector_agencies, ext_agencies,  "")
Rel(booking_interface, collector_agencies, "")
Rel_Back_Neighbor(collector_agencies, booking_tracker, "")
Rel_Back(booking_interface, booking_tracker, "")


Rel(analytics, booking_db, "")
Rel_Neighbor(booking_interface, booking_db, "")
booking_db -[hidden]-- mail_poller

third_parties -[hidden]-email_provider

Rel_Neighbor(third_parties, analytics, "monetizing data")
Rel_Back(customer, analytics, "")

Rel(customer, help, "")
Rel(help, booking_interface, "")
Rel_Back(notifier, booking_tracker, "")

Rel(customer, sharer, "")
Rel_Neighbor(sharer, social_media, "")







@enduml
