@startuml
!include <c4/C4_Component.puml>  
!theme aws-orange
skinparam BackgroundColor white
' uncomment the following line and comment the first to use locally
' !include C4_Component.puml

LAYOUT_WITH_LEGEND()

title Component diagram for for **Road Warrior** app\n - **Mail integration**


Container_Boundary(mail_integration, "Mail integration") {
Component(mail_poller, "Poller", "retrieve travel via mails", "Poll mail from the upstream provider")
Component(mail_listener, "Listener", "receive forwarded mail", "users allow forwarding mails to the system")
Component(mail_filter, "Filter", "select interesting mails", "can white/black list mails based on a predefined criterias")

    Rel(mail_poller, mail_filter, "Forward")
    Rel(mail_listener, mail_filter, "Forward")

}

Component(booking_engine, "Booking Engine", "MVC Rest Controller", "Access to all operation in and out of the Storage\n\nCrud operations")

System_Ext(email_provider, "E-mail provider", "User mail provider.")


Rel(mail_filter, booking_engine, "update")
Rel(email_provider, mail_listener, "Receiving mails")
Rel_Back(email_provider, mail_poller, "")



@enduml
